---
title: "Type1Tobit"
author: "Kei Sakamoto"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Type1 Tobit のコマンド2種類
###①vglm
###②censReg

```{r}
load("~/計量経済学演習/R data sets for 5e/mroz.RData")
mroz<-data
#install.packages("VGAM")
library(VGAM)
```

#Type1Tobit model
```{r}
Type1Tobit<-vglm(hours~nwifeinc+educ+exper+I(exper^2)+age+kidslt6+kidsge6,tobit(Lower=0),data=mroz)
summary(Type1Tobit)
```

```{r}
library(censReg)
TobitRes <- censReg(hours~nwifeinc+educ+exper+I(exper^2)+ 
                                    age+kidslt6+kidsge6, data=mroz )
summary(TobitRes)
```

###２つの方法で全く同じ結果を得られる。

## 説明変数複数あるので描画は不可能だが Monte Carlo Simuration で説明変数１つの状況を作って描画は可能。

```{r}
set.seed(93876553)
x<-sort(rnorm(100)+4)
xb<- -4+x
ystar<-xb+rnorm(100)
y<-ystar
y[ystar<0]=0 #bottom coding

Eystar<-xb #本当に欲しいのはこっち
Ey<-pnorm(xb/1)*xb+1*dnorm(xb/1)

plot(x,ystar,ylab="y",pch=3)
points(x,y,pch=1) #一部上書き
lines(x,Eystar,lty=2,lwd=2)
lines(x,Ey,lty=1,lwd=2)
abline(h=0,lty=3) #点のhorizontal line
legend("topleft",c(expression(y^"*"),"y",expression(E(y^"*")),"E(y)"),lty=c(NA,NA,2,1),pch=c(3,1,NA,NA),lwd=c(1,1,2,2))
```
